### ISSUE TITLE
won't compile on osx 10.10.1

### ISSUE THREAD

**Issue by kfirufk** [mscdex/node-mariasql#87]
CXX(target) Release/obj.target/sqlclient/src/binding.o
../src/binding.cc:165:23: error: expected class name
class Client : public ObjectWrap {
                      ^
../src/binding.cc:168:5: error: unknown type name 'uv_poll_t'
    uv_poll_t *poll_handle;
    ^
../src/binding.cc:169:5: error: unknown type name 'uv_os_sock_t'
    uv_os_sock_t mysql_sock;
    ^
../src/binding.cc:261:26: error: unknown type name 'uv_handle_t'
    static void cb_close(uv_handle_t *handle) {
                         ^
../src/binding.cc:564:25: error: unknown type name 'uv_poll_t'
    static void cb_poll(uv_poll_t *handle, int status, int events) {
                        ^
../src/binding.cc:798:36: error: unknown type name 'Arguments'; did you mean
      'v8::internal::Arguments'?
    static Handle<Value> New(const Arguments& args) {
                                   ^~~~~~~~~
                                   v8::internal::Arguments
/Users/ufk/.node-gyp/0.11.14/deps/v8/include/v8.h:127:7: note:
      'v8::internal::Arguments' declared here
class Arguments;
      ^
../src/binding.cc:818:39: error: unknown type name 'Arguments'; did you mean
      'v8::internal::Arguments'?
    static Handle<Value> Escape(const Arguments& args) {
                                      ^~~~~~~~~
                                      v8::internal::Arguments
/Users/ufk/.node-gyp/0.11.14/deps/v8/include/v8.h:127:7: note:
      'v8::internal::Arguments' declared here
class Arguments;
      ^
../src/binding.cc:840:40: error: unknown type name 'Arguments'; did you mean
      'v8::internal::Arguments'?
    static Handle<Value> Connect(const Arguments& args) {
                                       ^~~~~~~~~
                                       v8::internal::Arguments
/Users/ufk/.node-gyp/0.11.14/deps/v8/include/v8.h:127:7: note:
      'v8::internal::Arguments' declared here
class Arguments;
      ^
../src/binding.cc:980:43: error: unknown type name 'Arguments'; did you mean
      'v8::internal::Arguments'?
    static Handle<Value> AbortQuery(const Arguments& args) {
                                          ^~~~~~~~~
                                          v8::internal::Arguments
/Users/ufk/.node-gyp/0.11.14/deps/v8/include/v8.h:127:7: note:
      'v8::internal::Arguments' declared here
class Arguments;
      ^
../src/binding.cc:992:38: error: unknown type name 'Arguments'; did you mean
      'v8::internal::Arguments'?
    static Handle<Value> Query(const Arguments& args) {
                                     ^~~~~~~~~
                                     v8::internal::Arguments
/Users/ufk/.node-gyp/0.11.14/deps/v8/include/v8.h:127:7: note:
      'v8::internal::Arguments' declared here
class Arguments;
      ^
../src/binding.cc:1012:38: error: unknown type name 'Arguments'; did you mean
      'v8::internal::Arguments'?
    static Handle<Value> Close(const Arguments& args) {
                                     ^~~~~~~~~
                                     v8::internal::Arguments
/Users/ufk/.node-gyp/0.11.14/deps/v8/include/v8.h:127:7: note:
      'v8::internal::Arguments' declared here
class Arguments;
      ^
../src/binding.cc:1025:42: error: unknown type name 'Arguments'; did you mean
      'v8::internal::Arguments'?
    static Handle<Value> IsMariaDB(const Arguments& args) {
                                         ^~~~~~~~~
                                         v8::internal::Arguments
/Users/ufk/.node-gyp/0.11.14/deps/v8/include/v8.h:127:7: note:
      'v8::internal::Arguments' declared here
class Arguments;
      ^
../src/binding.cc:183:12: error: no member named 'Dispose' in
      'v8::Persistent<v8::Function,
      v8::NonCopyablePersistentTraits<v8::Function> >'
      Emit.Dispose();
      ~~~~ ^
../src/binding.cc:184:12: error: no member named 'Clear' in
      'v8::Persistent<v8::Function,
      v8::NonCopyablePersistentTraits<v8::Function> >'
      Emit.Clear();
      ~~~~ ^
../src/binding.cc:237:7: error: no member named 'Dispose' in
      'v8::Persistent<v8::String, v8::NonCopyablePersistentTraits<v8::String> >'
      FREE_PERSISTARRAY(cur_query.column_names, cur_query.column_count);
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/binding.cc:153:15: note: expanded from macro 'FREE_PERSISTARRAY'
              FREE_PERSIST(a[i]);                                             \
              ^~~~~~~~~~~~~~~~~~
../src/binding.cc:149:47: note: expanded from macro 'FREE_PERSIST'
#define FREE_PERSIST(h) if (!h.IsEmpty()) { h.Dispose(); h.Clear(); }
                                            ~ ^
../src/binding.cc:237:7: error: no member named 'Clear' in
      'v8::Persistent<v8::String, v8::NonCopyablePersistentTraits<v8::String> >'
      FREE_PERSISTARRAY(cur_query.column_names, cur_query.column_count);
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/binding.cc:153:15: note: expanded from macro 'FREE_PERSISTARRAY'
              FREE_PERSIST(a[i]);                                             \
              ^~~~~~~~~~~~~~~~~~
../src/binding.cc:149:60: note: expanded from macro 'FREE_PERSIST'
#define FREE_PERSIST(h) if (!h.IsEmpty()) { h.Dispose(); h.Clear(); }
                                                         ~ ^
../src/binding.cc:253:21: error: use of undeclared identifier 'uv_handle_t'
          uv_close((uv_handle_t*) poll_handle, cb_close);
                    ^
../src/binding.cc:253:33: error: expected expression
          uv_close((uv_handle_t*) poll_handle, cb_close);
                                ^
../src/binding.cc:262:19: error: calling a protected constructor of class
      'v8::HandleScope'
      HandleScope scope;
                  ^
/Users/ufk/.node-gyp/0.11.14/deps/v8/include/v8.h:816:13: note: declared
      protected here
  V8_INLINE HandleScope() {}
            ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/sqlclient/src/binding.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/opt/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1059:12)
gyp ERR! System Darwin 14.0.0
gyp ERR! command "node" "/opt/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/ufk/Projects/api.myalcoholist.com/node_modules/mariasql
gyp ERR! node -v v0.11.14
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
npm ERR! Darwin 14.0.0
npm ERR! argv "/opt/local/bin/node" "/opt/local/bin/npm" "install" "--save" "mariasql"
npm ERR! node v0.11.14
npm ERR! npm  v2.1.16
npm ERR! code ELIFECYCLE

npm ERR! mariasql@0.1.21 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mariasql@0.1.21 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the mariasql package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls mariasql
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/ufk/Projects/api.myalcoholist.com/npm-debug.log
Kfirs-MacBook-Pro:api.myalcoholist.com ufk$ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 6.0 (clang-600.0.56) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin14.0.0
Thread model: posix
Kfirs-MacBook-Pro:api.myalcoholist.com ufk$ which libtool
/usr/bin/libtool

**Comment by mscdex** [comment]
This addon isn't compatible with node v0.11.x yet.

**Comment by garrett-gottlieb** [comment]
+1

**Comment by kfirufk** [comment]
v0.12 is out. still not compatible

**Comment by mscdex** [comment]
Unfortunately new node/iojs releases do not increase the amount of free time to convert addons to nan ;-)

**Comment by mscdex** [comment]
Duplicate of #86.
